language: node_js

node_js:
  - "node"

before_script:
  - "mkdir dist"
  - "mkdir dist/installers"

jobs:
  include:
    - stage: buildWin
      os: windows
      script:
        - npm run build:windows
        - npm run package:win64

    - stage: buildMac
      os: osx
      script:
        - npm run build:mac
        - npm run package:mac64

    - stage: buildLinux
      os: linux
      before_script:
        - apt-get install fakeroot
      script:
        - npm run build:linux
        - npm run package:deb64
