language: node_js

node_js:
  - "node"

before_script:
  - "mkdir dist"
  - "mkdir dist/installers"

matrix:
  include:
    - os: windows
      script:
        - npm run build:windows
        - npm run package:win64
    - os: osx
      script:
        - npm run build:mac
        - npm run package:mac64
    - os: linux
      before_script:
        - sudo apt-get update
        - sudo apt-get install fakeroot
      script:
        - npm run build:linux
        - npm run package:deb64
