language: node_js

node_js:
  - "node"

before_script:
  - "mkdir dist"
  - "mkdir dist/installers"

  stages:
    - test
    - build

jobs:
  include:
    - stage: test
      script: npm run test:ci
      os: osx
    
    - stage: build
      if: os = osx 
      os: osx
      script:
        - npm run build:mac
        - npm run package:mac64
    
    - stage: build
      if: os = windows
      os: windows
      script:
        - npm run build:windows
        - npm run package:win64
    
    - stage: build
      if: os = linux
      os: linux
      before_script:
        - sudo apt-get update
        - sudo apt-get install fakeroot
      script:
        - npm run build:linux
        - npm run package:deb64
