language: node_js

node_js:
  - "node"

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode9.0
      script: npm run test:ci

    - stage: build
      os: linux
      script: npm run dist
      deploy:
        provider: releases
        api_key: "GITHUB OAUTH TOKEN"
        file:
          - dist/switchql_1.0.0_amd64.snap
          - dist/switchql 1.0.0.AppImage
        skip_cleanup: true
        on:
          tags: true

    - stage: build
      os: osx
      script: npm run dist
      deploy:
        provider: releases
        api_key: "GITHUB OAUTH TOKEN"
        file: dist/switchql-1.0.0.dmg
        skip_cleanup: true
        on:
          tags: true

    - stage: build
      os: windows
      script: npm run dist
      deploy:
        provider: releases
        api_key: "GITHUB OAUTH TOKEN"
        file: dist\switchql Setup 1.0.0.exe
        skip_cleanup: true
        on:
          tags: true
