language: node_js

node_js:
  - "node"

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode9.0
      script: npm run test:ci

    - stage: build
      os: linux
      script: npm run dist

    - stage: build
      os: osx
      script: npm run dist

    - stage: build
      os: windows
      script: npm run dist
